name: "Run tfsec"
description: "Scan your Terraform code for vulnerabilities with tfsec"

branding:
  icon: "check"
  color: "purple"

author: "Svetlin Ralchev"

inputs:
  working_directory:
    description: Current working directory that contains the terraform source code
    required: false
    default: "."
  config_file:
    description: "The path to the config file."
    required: false
  report_file:
    description: "The path to write the report."
    required: false
  report_format:
    description: "The report format (default, json, csv, checkstyle, junit, sarif)."
    required: false
  tfsec_args:
    description: "Space seperated args specified here will be added during tfsec execution."
    required: false

outputs:
  tfsec-return-code:
    description: "tfsec command return code"

runs:
  using: "docker"
  image: "Dockerfile"
